SEMANTIC_MODEL = {
    "measures": {
        "revenue": {
            "expression": "SUM(f.revenue)",
            "description": "Total revenue generated by the business",
            "table": "fact_revenue"
        },
        "cost": {
            "expression": "SUM(f.cost)",
            "description": "Total cost associated with revenue",
            "table": "fact_revenue"
        },
        "profit": {
            "expression": "SUM(f.profit)",
            "description": "Total profit",
            "table": "fact_revenue"
        }
    },

    "dimensions": {
        "region": {
            "column": "r.region_name",
            "table": "dim_region",
            "values": ["APAC", "EMEA", "Americas"]
        },
        "quarter": {
            "column": "f.quarter",
            "table": "fact_revenue",
            "values": ["Q1", "Q2"]
        },
        "year": {
            "column": "f.year",
            "table": "fact_revenue"
        },
        "client": {
            "column": "c.client_name",
            "table": "dim_client"
        },
        "product": {
            "column": "p.product_name",
            "table": "dim_product"
        }
    }
}


if __name__ == "__main__":
    print("Available measures:")
    for name, definition in SEMANTIC_MODEL["measures"].items():
        print(f" - {name}: {definition['description']}")

    print("\nAvailable dimensions:")
    for name in SEMANTIC_MODEL["dimensions"]:
        print(f" - {name}")