SEMANTIC_MODEL = {
    "measures": {
        "revenue": {
            "expression": "COALESCE(SUM(f.REVENUE), 0)",
            "description": "Total revenue generated by the business",
            "table": "FACT_SALES"
        }
    },

    "dimensions": {
        "region": {
            "column": "r.REGION_NAME",
            "table": "DIM_REGION",
            "join": "f.REGION_KEY = r.REGION_KEY"
        },

        "client": {
            "column": "c.CUSTOMER_NAME",
            "table": "DIM_CUSTOMER",
            "join": "f.CUSTOMER_KEY = c.CUSTOMER_KEY"
        },

        "product": {
            "column": "p.PRODUCT_NAME",
            "table": "DIM_PRODUCT",
            "join": "f.PRODUCT_KEY = p.PRODUCT_KEY"
        },

        "date": {
            "column": "f.SALE_DATE",
            "table": "FACT_SALES"
        }
    },

    "time_logic": {
        "year": "Filter using f.SALE_DATE for the requested calendar year.",
        "quarter": {
            "Q1": "January 1 through March 31",
            "Q2": "April 1 through June 30",
            "Q3": "July 1 through September 30",
            "Q4": "October 1 through December 31"
        }
    }
}


if __name__ == "__main__":

    print("Available measures:")

    for name, definition in SEMANTIC_MODEL["measures"].items():
        print(f" - {name}: {definition['description']}")

    print("\nAvailable dimensions:")

    for name in SEMANTIC_MODEL["dimensions"]:
        print(f" - {name}")